export const formStatus = {
  ADD: "ADD",
  VIEW: "VIEW",
  EDIT: "EDIT",
  EDIT_BASIC_INFO: "EDIT_BASIC_INFO",
  EDIT_DATA_PERMISSION: "EDIT_DATA_PERMISSION",
  VIEW_DATA_PERMISSION: "VIEW_DATA_PERMISSION"
};
